
version: '3'

services:

#  elasticsearch-app:
#    build: .
#    container_name: elasticsearch-app
#    ports:
#      - "18080:8080"
#      - "18089:8089"
#    depends_on:
#      - elasticsearch
#    networks:
#      - elknet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      # - discovery.type=single-node
      # - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      # - xpack.security.transport.ssl.enabled=true

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data 
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      - elasticsearch.username="admin"
      - elasticsearch.password="123"
      - ELASTICSEARCH_URL="http://elasticsearch:9300"
      - xpack.security.enabled=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elknet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - elknet

volumes:
  esdata1:
    driver: local

networks:
  elknet: