version: '3'
services:
  mssql:
    container_name: mssqldev
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - bedata1:/var/opt/mssql/data
    ports: 
     - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=reallyStrongPwd123
#      - MSSQL_PID=Express

    networks:
      - servernet
  springboot-app:
    #    container_name: spring-app
    image: trace.origin:1.1.0
    restart: always
    depends_on:
      - mssql
    build: .
    ports:
      - 8080:8080


volumes:
  bedata1:
    driver: local

networks:
  servernet:
    
